### ISSUE TITLE
Problematic behavior on failed requests

### ISSUE THREAD

**Issue by michaelernst** [Uniscon/cert-manager-webhook-hostingde#1]
Hi,

the integration handles failed requests not well. We have experienced DOS like behavior from customers using this integration several times. It seems that when the API key does not exist or the IP address is not whitelisted the integration goes into a loop make one request after another - which leads to an IP ban in the end. The same applies to the fact when the ZoneConfig object does not exist or is not writable.

Please check the integration and implement a more graceful error handling.

**Comment by jkahrs** [comment]
This might be similar to https://github.com/jetstack/cert-manager/issues/3222 / https://github.com/jetstack/cert-manager/pull/3485

**Comment by sibiantony** [comment]
Sorry for the delay in reply, the webhook is no longer in use and is not maintained. This repository will be archived.
