### ISSUE TITLE
Installation fails on current K3s

### ISSUE THREAD

**Issue by realulim** [Uniscon/cert-manager-webhook-hostingde#3]
`helm install --namespace cert-manager cert-manager-webhook-hostingde deploy/cert-manager-webhook-hostingde`

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "APIService" in version "apiregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha3", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha3"]`

K3s version: v1.23.5+k3s1
Cert-Manager: v1.8.0
OS: Rocky Linux release 8.5

**Comment by sibiantony** [comment]
The project was only intended to be used on Kubernetes. And there were no plans for porting to other flavors.
Also the project is no longer maintained.
